/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as SessionDiagnosisRouteImport } from './routes/session/diagnosis'
import { Route as SessionLearnRouteImport } from './routes/session/learn'
import { Route as SessionProbeRouteImport } from './routes/session/probe'
import { Route as SessionQuestionRouteImport } from './routes/session/question'
import { Route as SessionReassessRouteImport } from './routes/session/reassess'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionDiagnosisRoute = SessionDiagnosisRouteImport.update({
  id: '/session/diagnosis',
  path: '/session/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionLearnRoute = SessionLearnRouteImport.update({
  id: '/session/learn',
  path: '/session/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionProbeRoute = SessionProbeRouteImport.update({
  id: '/session/probe',
  path: '/session/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionQuestionRoute = SessionQuestionRouteImport.update({
  id: '/session/question',
  path: '/session/question',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionReassessRoute = SessionReassessRouteImport.update({
  id: '/session/reassess',
  path: '/session/reassess',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/session/diagnosis': typeof SessionDiagnosisRoute
  '/session/learn': typeof SessionLearnRoute
  '/session/probe': typeof SessionProbeRoute
  '/session/question': typeof SessionQuestionRoute
  '/session/reassess': typeof SessionReassessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/session/diagnosis': typeof SessionDiagnosisRoute
  '/session/learn': typeof SessionLearnRoute
  '/session/probe': typeof SessionProbeRoute
  '/session/question': typeof SessionQuestionRoute
  '/session/reassess': typeof SessionReassessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/evaluation': typeof EvaluationRoute
  '/session/diagnosis': typeof SessionDiagnosisRoute
  '/session/learn': typeof SessionLearnRoute
  '/session/probe': typeof SessionProbeRoute
  '/session/question': typeof SessionQuestionRoute
  '/session/reassess': typeof SessionReassessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/evaluation'
    | '/session/diagnosis'
    | '/session/learn'
    | '/session/probe'
    | '/session/question'
    | '/session/reassess'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/evaluation'
    | '/session/diagnosis'
    | '/session/learn'
    | '/session/probe'
    | '/session/question'
    | '/session/reassess'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/evaluation'
    | '/session/diagnosis'
    | '/session/learn'
    | '/session/probe'
    | '/session/question'
    | '/session/reassess'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EvaluationRoute: typeof EvaluationRoute
  SessionDiagnosisRoute: typeof SessionDiagnosisRoute
  SessionLearnRoute: typeof SessionLearnRoute
  SessionProbeRoute: typeof SessionProbeRoute
  SessionQuestionRoute: typeof SessionQuestionRoute
  SessionReassessRoute: typeof SessionReassessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/diagnosis': {
      id: '/session/diagnosis'
      path: '/session/diagnosis'
      fullPath: '/session/diagnosis'
      preLoaderRoute: typeof SessionDiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/learn': {
      id: '/session/learn'
      path: '/session/learn'
      fullPath: '/session/learn'
      preLoaderRoute: typeof SessionLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/probe': {
      id: '/session/probe'
      path: '/session/probe'
      fullPath: '/session/probe'
      preLoaderRoute: typeof SessionProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/question': {
      id: '/session/question'
      path: '/session/question'
      fullPath: '/session/question'
      preLoaderRoute: typeof SessionQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/reassess': {
      id: '/session/reassess'
      path: '/session/reassess'
      fullPath: '/session/reassess'
      preLoaderRoute: typeof SessionReassessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EvaluationRoute: EvaluationRoute,
  SessionDiagnosisRoute: SessionDiagnosisRoute,
  SessionLearnRoute: SessionLearnRoute,
  SessionProbeRoute: SessionProbeRoute,
  SessionQuestionRoute: SessionQuestionRoute,
  SessionReassessRoute: SessionReassessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
